version: 2
jobs:

  test-php74:
    docker:
      - image: circleci/php:7.4-cli
      - image: rabbitmq

    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Run tests
          command: |
            composer update -n --prefer-dist --no-suggest
            php vendor/bin/phpunit

  test-php80:
    docker:
      - image: circleci/php8.0-cli
      - image: rabbitmq

    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Run tests
          command: |
            composer update -n --prefer-dist --no-suggest
            php vendor/bin/phpunit

workflows:
  version: 2
  test:
    jobs:
      - test-php74
      - test-php80