version: 2
jobs:

  test:
    parameters:
      php-version:
        type: string
    docker:
      - image: cimg/php:<< parameters.php-version >>
      - image: rabbitmq:3
        environment:
          RABBITMQ_VHOST: /
          RABBITMQ_USERNAME: guest
          RABBITMQ_PASSWORD: guest

    working_directory: ~/project

    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            composer update -n --prefer-dist
            php vendor/bin/phpunit

workflows:
  version: 2
  test:
    jobs:
      - test:
          matrix:
            parameters:
              php-version: ["7.4", "8.0"]
